yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'password/reset/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текс поста',
            'group': 'Группа',
        }
        help_text = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self):
        context = {
            'title': 'Об авторе проекта'
        }
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self):
        context = {
            'title': 'Технологии'
        }
        return context

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth.models import User

from .models import Group, Post
from .forms import PostForm

COUNTER_POSTS = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, COUNTER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Главная страница Yatube',
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, COUNTER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': group.title,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(
        author__username=username).all()
    paginator = Paginator(post_list, COUNTER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user_profile': user_profile,
        'username': username,
        'title': f'Профайл пользователя {username}',
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_text = post.text[:30]
    context = {
        'title': f'Пост {post_text}',
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form, 'title': 'Новый пост'})
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect(f'/profile/{request.user}/')


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
                      'form': form,
                      'title': 'Редактировать пост',
                      'is_edit': True,
                      'post': post})
    form.save()
    return redirect('posts:post_detail', post_id)

yatube/users/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

    def get_context_data(self):
        context = {
            'title': 'Зарегистрироваться'
        }
        return context


class PasswordChange(PasswordChangeView):
    success_url = 'done/'
    template_name = 'user/password_change_done.html'

    def get_context_data(self):
        context = {
            'title': 'Сброс пароля'
        }
        return context

yatube/templates/about/author.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1>Привет, я Елена!</h1>
<p>
  <br />Всегда интересовалась сферой ИТ. Получила два высших образования, защитила кандидатскую диссертацию, а теперь решила попробовать себя в роли backend-разработчика.
</p>
<p>
  Моё резюме доступно <a href="https://volgograd.hh.ru/resume/93be40e7ff08f44f940039ed1f3963436a464d">здесь</a>
  <br />Мои проекты можно посмотреть на <a href="https://github.com/ElenaVasilkova">GitHub</a>
  <br />Мой профиль <a href="https://vk.com/id373108781">ВКонтакте</a>
</p>
<p>
  В свободное время я люблю спать. 
  <br />Чёрно-белый пёс и серый попугай делают мой мир более радужным.
</p>
<p>
    <img src="{% static "img/photo.png" %}" width="640" height="640" alt="img">
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{% load static %}
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5"> 
      {% block content %}
      {% endblock %} 
      </div>
    </main>
    <footer>
      {%include 'includes/footer.html'%}
    </footer>
  </body>
</html>

yatube/templates/includes/errors_form.html
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<!--includes/footer.html-->
<footer class="page-footer font-small border-top text-center py-3">
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  {%load static%}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link
            {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == 'posts:post_create' %}active{% endif %}" 
          href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:password_reset' %}"
          >Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}"
          >Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}     
    </div>
  </nav>      
</header>

yatube/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_card.html
<article>
    <ul>
      <li>
        Автор: {{ post.author.first_name}} {{ post.author.last_name}}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}"
    >подробная информация</a>
    </article>
    {% if post.group %}
      <p>
      <a href="{% url 'posts:group_posts' post.group.slug %}"
      >все записи группы {{ post.group.title }}</a> 
      </p>       
    {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">       
        {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
      </div>
      <div class="card-body">
        
        <form method="post" action=
          {% if is_edit %} 
          {% url 'posts:post_edit' form.instance.pk %}
        {% else %}
          {% url 'posts:post_create' %}
        {% endif %}>
        {% include 'includes/errors_form.html' %}
        {% csrf_token %}
          
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_lable }}">
                {{ field.label }}
                {% if field.field.required %}
                <span class="required text-danger">*</span>
                {% endif %}                  
              </label>
              <div>
                {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}                            
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}               
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block content %}  
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    <br></br>
    <article>
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
      {% endfor %}
    </article>
    {% include 'includes/paginator.html' %}
  {% endblock %} 

yatube/templates/posts/index.html
{% extends "base.html" %}
  {% block content %}   
    <h1>Последние обновления на сайте</h1>
    <br></br>
    <article>
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
      {% endfor %}
    </article>
    {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                <p> все записи группы </p>
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.first_name}} {{ post.author.last_name}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя {{ post.user_profile.get_full_name }}
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text }}
          </p>
          {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              Редактировать пост
            {% endif %}               
        </a>
      </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content %} 
        <h1>Все посты пользователя: {{ user_profile.get_full_name }} </h1>
        <h3>Всего постов: {{ user_profile.posts.count }} </h3>
        {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        {% include 'includes/errors_form.html' %}
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/errors_form.html' %}

            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
            </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            Пароль изменён
        </div>
        <div class="card-body"> 
          {% include 'includes/errors_form.html' %}
            {% csrf_token %}

            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменить пароль{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          {% include 'includes/errors_form.html' %}
          <form method="post" action="{% url 'users:password_change_form' %}">
          {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>

            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>

            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            Восстановление пароля завершено
        </div>
        <div class="card-body">
          {% include 'includes/errors_form.html' %}
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          {% csrf_token %}
          <a href="../users/login.html">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            Введите новый пароль
        </div>
        <div class="card-body">
          {% include 'includes/errors_form.html' %}
          <form method="post" action="{% url 'users:password_reset_confirm' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>      
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
        </div> 
      </div> 
    </div>
  </div> 
  <!-- если использована неправильная ссылка -->
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  <!-- конец если использована неправильная ссылка -->

{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}

{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
            {% include 'includes/errors_form.html' %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}